name = "cargameonline"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "app"

[build.upload]
format = "directory"
dir = "./out"

[[build.environment_variables]]
NODE_VERSION = "18"
